package mdb

const (
	StatusWaitPay     = 1
	StatusPaySuccess  = 2
	StatusExpired     = 3
	CallBackConfirmOk = 1
	CallBackConfirmNo = 2
)

const (
	PaymentTypeEpay = "Epay"
)

type Orders struct {
	TradeId            string  `gorm:"column:trade_id;uniqueIndex:orders_trade_id_uindex" json:"trade_id"`
	OrderId            string  `gorm:"column:order_id;uniqueIndex:orders_order_id_uindex" json:"order_id"` // the order id is generated by client, and will notify client when order is paid
	BlockTransactionId string  `gorm:"index:orders_block_transaction_id_index;column:block_transaction_id" json:"block_transaction_id"`
	Amount             float64 `gorm:"column:amount" json:"amount"`
	Currency           string  `gorm:"column:currency" json:"currency"`
	ActualAmount       float64 `gorm:"column:actual_amount" json:"actual_amount"`
	ReceiveAddress     string  `gorm:"column:receive_address" json:"receive_address"`
	Token              string  `gorm:"column:token" json:"token"`
	Network            string  `gorm:"column:network" json:"network"`
	Status             int     `gorm:"column:status;default:1" json:"status"`
	NotifyUrl          string  `gorm:"column:notify_url" json:"notify_url"`
	RedirectUrl        string  `gorm:"column:redirect_url" json:"redirect_url"`
	Name               string  `gorm:"column:name" json:"name"`
	CallbackNum        int     `gorm:"column:callback_num;default:0" json:"callback_num"`
	CallBackConfirm    int     `gorm:"column:callback_confirm;default:2" json:"callback_confirm"`
	PaymentType        string  `gorm:"column:payment_type" json:"payment_type"`
	BaseModel
}

func (o *Orders) TableName() string {
	return "orders"
}
